### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by schtritoff** [ColiseoSoftware/hypervbackup#10]
Is it possible to document code, especially for methods in class [BackupClasss.cs](https://github.com/ColiseoSoftware/hypervbackup/blob/master/HyperVBackup.Engine/BackupManager.cs)? Maybe one-line description for some important stuff that is going on like recursion in finding paths, how paths are found for virtual machine, etc. I looked for original code which you forked and I understand that you inherited the lack of documentation. It would be easier for someone else to pick up and extend the app.

**Comment by pablopioli** [comment]
Sure, but I'm short of free time and currently I'm working in including logging capabilities.
