### ISSUE TITLE
Differential backup - feature request

### ISSUE THREAD

**Issue by schtritoff** [ColiseoSoftware/hypervbackup#11]
I thought about implementing differential backup (and the docs are not helping much, as [mentioned](https://github.com/ColiseoSoftware/hypervbackup/issues/10)). For very big VM it is not practical making full backup every day. Idea is: use 7z create tar archive of VM files (infrastructure for volume shadow per VM is already here, also 7z) then use [PIGZ --rsyncable](https://blog.kowalczyk.info/software/pigz-for-windows.html) for fast, delta encoding friendly compression and finally use [xdelta3 ](https://github.com/jmacd/xdelta-gpl/releases/tag/v3.0.11)for making deltas.

I have nearly ready batch script for this scenario but I lack VSS per VM (I'm making VSS for whole drive), discovering VM files, etc - things that are already backed here.

Command line example for full backup:
`7z.exe a dummy -r -ttar -so "folder_to_backup" | pigz.exe -2 -c -f -R > \\backupsrv\share1\folder_to_backup.full.tar.gz`

Command line example for differential backup:
`7z.exe a dummy -r -ttar -so ""folder_to_backup"" | pigz.exe -2 -c -f -R | xdelta3-3.0.11-x86_64.exe -D -f -S -s \\backupsrv\share1\folder_to_backup.full.tar.gz > \\backupsrv\share1\folder_to_backup.1.diff`

**Comment by pablopioli** [comment]
I'm not sure how reliable is a differential backup of a virtual hard disk. Until now I prefer to split the data in different VHD's and only copy those I want.

But I will love to test it. What you need to try it?

As far as I know VSS only offers you a snapshopt of the whole drive. This gives you a start
http://ariely.info/Blog/tabid/83/EntryId/137/AlphaVSS-Basic-Code-Examples.aspx

**Comment by pablopioli** [comment]
In 
https://msdn.microsoft.com/en-us/library/aa382650(v=vs.85).aspx
you can see what you can include in the snapshot
