### ISSUE TITLE
backups on the lan or only local ?

### ISSUE THREAD

**Issue by stephane78** [ColiseoSoftware/hypervbackup#14]
Hi,
I have a question,does Hypervbackup runs only on an Hyperv server (windows server) and do backup on this hyperv server or is it possible to do backup of hyperv servers on the lan with hypervbackup running on another computer (client or server) ?

**Comment by pablopioli** [comment]
You can backup anywhere Windows can write a file. So you can easily store the output in a shared folder, as in \\\server\\folder, provided the process has write permissions.

You can store the output on another disk of the server (defeating the purpose of the backup operation), and even in the same disk containing the virtual machine (slows down the backup operation a lot)

**Comment by stephane78** [comment]
thanks pablopioli,but my question was : does hyperv run only on a windows server (hyperv server) or does it run on a client hyper v(windows 10 for example) and do backup of hyperv servers that are on the lan?

**Comment by pablopioli** [comment]
The original creators never developed it as a client/server utility. It only runs from a local server. 

You can, however, execute a remote powershell command and run the backup from another machine. 

In development are logging capabilities that could be used to monitor the progress of the backup from another machine, if this is useful to you.

**Comment by stephane78** [comment]
ok thanks pablopioli....
