### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by hulmgulm** [ColiseoSoftware/hypervbackup#16]
Hi,

I have a question which I could not find the answer to:

How do I restore the VMs I backed up with this tool?

On the same machine as the backup is comming from, it looks like I just have to unzip the file and overwrite the existing files. Will this work?

How do I restore on a different PC?

Thank you,
  Andreas

**Comment by var-log-skynet** [comment]
On the same machine it _might_ work however the process is: 

Unzip the files and in Hyper-V manager choose Import Virtual Machine. Browse the folder you just unzipped.

**Comment by pablopioli** [comment]
In the same machine:

* If the VM is still registered you can simply overwrite the virtual hard disk files
* If you are restoring to a new virtual machine use HyperV's Import Wizard. It takes care of all the details.

In another machine:

* Use HyperV's Import Wizard

In the original machine it will always work. In another machine depends on the guest OS and how different are the hardware of the machines. A VM of Windows 10 created in an Intel box, probably won't boot in an AMD box. So you have more chances if the machines are similar.

In the worst case you can mount the VHD files and copy files from there.
