### ISSUE TITLE
command line switches - prefix

### ISSUE THREAD

**Issue by schtritoff** [ColiseoSoftware/hypervbackup#5]
It should be noted on help screen that command line option should be prefixed with double dash "--". Some works with 1 dash only but for example compression level didn't work with one dash, only with two dashed. Its not clear from help screen.

**Comment by pablopioli** [comment]
Yes, you're right, but this is the original help screen.

Please collaborate, write a better help and I will include it.
More examples are welcome too.

**Comment by pablopioli** [comment]
I added a new description line to help new users understand how to use the switches.
It will be in the new release (it is already in the source code)
